#!/bin/bash
# =====================================================================
# Mega matrix — run ALL backbones in weights/ folder sequentially
#
# Discovers every mega_matrix/weights/<name>.pth, then dispatches:
#   - bash mega_matrix/run.sh        --backbone <name>     (single GPU, default)
#   - bash mega_matrix/run_ddp.sh    --backbone <name>     (multi-GPU)
#
# Per-backbone outputs land at:
#   outputs/_mega_matrix/<backbone>/
#     model_train{N}_{sel}/T*/best_model.pth + eval_{N}/
#   outputs/_mega_matrix/logs/
#     YYYYMMDD_HHMMSS_pidPID_<backbone>_run.log
#     YYYYMMDD_HHMMSS_pidPID_<backbone>_run_ddp.log(.train/.gpuN)
#     model_pseudo_{sel}/... and pseudo_train/ only with --with-pseudo
# Shared data (regardless of backbone):
#   outputs/_mega_matrix/train_n{50,100,200}/
#   outputs/_mega_matrix/eval_n{200,2000,20000}/
#
# Usage on server:
#   bash mega_matrix/run_all.sh                   # all backbones, single GPU
#   bash mega_matrix/run_all.sh --gpus 4          # all backbones, DDP 4 GPU
#   bash mega_matrix/run_all.sh --only convnext   # only backbones matching substring
#   bash mega_matrix/run_all.sh --with-pseudo     # forward to inner script
#   bash mega_matrix/run_all.sh --data-base data/wm-811k
#   bash mega_matrix/run_all.sh --skip-data       # data already generated
#
# Data is generated ONCE (during first backbone) and reused (--skip-data
# auto-applied for subsequent backbones).
# =====================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJ_ROOT"

WEIGHTS_DIR="mega_matrix/weights"
ONLY=""
NGPU=0
FORWARD_ARGS=()
while [ $# -gt 0 ]; do
    case $1 in
        --only) shift; ONLY="$1" ;;
        --only=*) ONLY="${1#--only=}" ;;
        --gpus) shift; NGPU="$1" ;;
        --gpus=*) NGPU="${1#--gpus=}" ;;
        *) FORWARD_ARGS+=("$1") ;;
    esac
    shift
done

# Auto-detect GPU count if --gpus not given
if [ "$NGPU" = "0" ]; then
    NGPU=$(nvidia-smi -L 2>/dev/null | wc -l 2>/dev/null || echo 1)
    [ "$NGPU" -lt 1 ] && NGPU=1
fi

# Pick inner runner
if [ "$NGPU" -ge 2 ]; then
    RUNNER="bash $SCRIPT_DIR/run_ddp.sh --gpus $NGPU"
else
    RUNNER="bash $SCRIPT_DIR/run.sh"
fi

OUT_BASE="outputs/_mega_matrix"
RUN_STAMP=$(date +%Y%m%d_%H%M%S)
LOG_DIR="$OUT_BASE/logs"
SUMMARY="$LOG_DIR/${RUN_STAMP}_run_all_summary.log"
mkdir -p "$OUT_BASE" "$LOG_DIR"
: > "$SUMMARY"
echo "$(date '+%Y-%m-%d %H:%M:%S') [run_all] start NGPU=$NGPU runner='$RUNNER'" | tee -a "$SUMMARY"

# Discover backbones
shopt -s nullglob
PTHS=("$WEIGHTS_DIR"/*.pth)
shopt -u nullglob
if [ ${#PTHS[@]} -eq 0 ]; then
    echo "[run_all] ERROR: no .pth in $WEIGHTS_DIR/" | tee -a "$SUMMARY"
    echo "[run_all] run 'python mega_matrix/download.py' on an internet machine first." | tee -a "$SUMMARY"
    exit 1
fi

# Filter
BACKBONES=()
for p in "${PTHS[@]}"; do
    name=$(basename "$p" .pth)
    if [ -n "$ONLY" ] && [[ "$name" != *"$ONLY"* ]]; then
        continue
    fi
    BACKBONES+=("$name")
done

if [ ${#BACKBONES[@]} -eq 0 ]; then
    echo "[run_all] ERROR: no backbones match --only '$ONLY'" | tee -a "$SUMMARY"
    exit 1
fi

echo "[run_all] backbones: ${BACKBONES[*]}" | tee -a "$SUMMARY"

IS_FIRST=1
for B in "${BACKBONES[@]}"; do
    START=$(date +%s)
    echo "" | tee -a "$SUMMARY"
    echo "============================================================" | tee -a "$SUMMARY"
    echo "$(date '+%Y-%m-%d %H:%M:%S') [run_all] >>> $B" | tee -a "$SUMMARY"
    echo "============================================================" | tee -a "$SUMMARY"

    EXTRA=()
    if [ $IS_FIRST -eq 0 ]; then
        # Data already generated by first backbone — reuse
        EXTRA+=("--skip-data")
    fi

    if $RUNNER --backbone "$B" "${FORWARD_ARGS[@]}" "${EXTRA[@]}" 2>&1 | tee -a "$SUMMARY"; then
        STATUS="OK"
    else
        STATUS="FAIL"
    fi
    ELAPSED=$(( $(date +%s) - START ))
    echo "$(date '+%Y-%m-%d %H:%M:%S') [run_all] $B $STATUS (${ELAPSED}s)" | tee -a "$SUMMARY"
    IS_FIRST=0
done

echo "" | tee -a "$SUMMARY"
echo "$(date '+%Y-%m-%d %H:%M:%S') [run_all] ALL BACKBONES DONE" | tee -a "$SUMMARY"
echo "[run_all] per-backbone outputs at outputs/_mega_matrix/<backbone>/" | tee -a "$SUMMARY"
echo "[run_all] summary: $SUMMARY" | tee -a "$SUMMARY"
